name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write 
  issues: write   
  checks: write   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests Report
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Create an issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/test-failure-template.md 

      - name: Publish App
        if: success()
        run: dotnet publish HelloDevOps.csproj -c Release -o ./publish_output

      - name: Create Release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          artifacts: "publish_output/*" 
          tag: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}